/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 phone.glb -T 
Files: phone.glb [270.75KB] > /Users/herman_mac/Documents/portfolio-site/public/models/phone-transformed.glb [22.01KB] (92%)
Author: FreeMeshBase (https://sketchfab.com/FreeMeshBase)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fmb-retro-phone-01-5ec4429f643440429a1baa940d90e5bb
Title: FMB_Retro Phone_01
*/

import { useGLTF } from "@react-three/drei";

export function Phone(props) {
  const { nodes, materials } = useGLTF("/models/phone-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.FMB_Retro_Phone_01_BW_01_0.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={9}
      />
    </group>
  );
}

useGLTF.preload("/phone-transformed.glb");
