/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 8_bit_dj.glb 
Author: FuneralClown (https://sketchfab.com/FuneralClown)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/8-bit-dj-cb5bc65d18134a02975a27f29cebf5e1
Title: 8 bit DJ
*/

import { useGLTF } from "@react-three/drei";

export function BitDJ(props) {
  const { nodes, materials } = useGLTF("models/8_bit_dj.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[2.887, 1.49, 3.64]}
        rotation={[-Math.PI / 2, -0.108, 0]}
        scale={69.048}
      >
        <mesh
          geometry={nodes.Cube018_Gameboy_bc002_0.geometry}
          material={materials["Gameboy_bc.002"]}
        />
        <mesh
          geometry={nodes.Cube018_Gameboy_bevelc001_0.geometry}
          material={materials["Gameboy_bevelc.001"]}
        />
        <mesh
          geometry={nodes.Cube018_Marshall_dc2002_0.geometry}
          material={materials["Marshall_dc2.002"]}
        />
        <mesh
          geometry={nodes.Cube018_8bit001_0.geometry}
          material={materials["8bit.001"]}
        />
        <mesh
          geometry={nodes.Cube018_Marshall_bc002_0.geometry}
          material={materials["Marshall_bc.002"]}
        />
        <mesh
          geometry={nodes.Cube018_Gameboy_dc002_0.geometry}
          material={materials["Gameboy_dc.002"]}
        />
        <mesh
          geometry={nodes.Cube018_Gameboy_bc003_0.geometry}
          material={materials["Gameboy_bc.003"]}
        />
        <mesh
          geometry={nodes.Cube018_Gameboy_dc003_0.geometry}
          material={materials["Gameboy_dc.003"]}
        />
        <mesh
          geometry={nodes.Cube018_Red001_0.geometry}
          material={materials["Red.001"]}
        />
        <mesh
          geometry={nodes.Cube018_Metal001_0.geometry}
          material={materials["Metal.001"]}
        />
        <mesh
          geometry={nodes.Cube018_Material002_0.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Cube018_P001_0.geometry}
          material={materials["P.001"]}
        />
        <mesh
          geometry={nodes.Cube018_Marshall_dc001_0.geometry}
          material={materials["Marshall_dc.001"]}
        />
        <mesh
          geometry={nodes.Cube018_Marshall_dc2003_0.geometry}
          material={materials["Marshall_dc2.003"]}
        />
        <mesh
          geometry={nodes.Cube018_Marshall_bc003_0.geometry}
          material={materials["Marshall_bc.003"]}
        />
        <mesh
          geometry={nodes.Cube018_MS_bc2001_0.geometry}
          material={materials["MS_bc2.001"]}
        />
        <mesh
          geometry={nodes.Cube018_MS_bc002_0.geometry}
          material={materials["MS_bc.002"]}
        />
        <mesh
          geometry={nodes.Cube018_MS_bc003_0.geometry}
          material={materials["MS_bc.003"]}
        />
        <mesh
          geometry={nodes.Cube018_Material_Marshall001_0.geometry}
          material={materials["Material_Marshall.001"]}
        />
      </group>
      <group
        position={[2.887, 1.49, 3.64]}
        rotation={[-Math.PI / 2, -0.108, 0]}
        scale={69.048}
      >
        <mesh
          geometry={nodes.Cube001_Material003_0.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Cube001_Material003_0_1.geometry}
          material={materials["Material.003"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/8_bit_dj.glb");
