/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 8_bit_dj.glb -T 
Files: 8_bit_dj.glb [9.39MB] > /Users/herman_mac/Documents/portfolio-site/public/models/8_bit_dj-transformed.glb [561.95KB] (94%)
Author: FuneralClown (https://sketchfab.com/FuneralClown)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/8-bit-dj-cb5bc65d18134a02975a27f29cebf5e1
Title: 8 bit DJ
*/

import { useGLTF } from "@react-three/drei";

export function BitDJ(props) {
  const { nodes, materials } = useGLTF("/models/8_bit_dj-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube018_Gameboy_bc002_0.geometry}
        material={materials.PaletteMaterial001}
        position={[2.887, 1.49, 3.64]}
        rotation={[-Math.PI / 2, -0.108, 0]}
        scale={69.048}
      />
      <mesh
        geometry={nodes.Cube018_8bit001_0.geometry}
        material={materials["8bit.001"]}
        position={[2.887, 1.49, 3.64]}
        rotation={[-Math.PI / 2, -0.108, 0]}
        scale={69.048}
      />
      <mesh
        geometry={nodes.Cube001_Material003_0.geometry}
        material={materials.PaletteMaterial002}
        position={[2.887, 1.49, 3.64]}
        rotation={[-Math.PI / 2, -0.108, 0]}
        scale={69.048}
      />
    </group>
  );
}

useGLTF.preload("/8_bit_dj-transformed.glb");
